import type { SeedInput } from './seeds';

// Architecture-first cases use the full classic discovery → options → ADR → portfolio workflow.
const decisions = [
  [
    'cloud-api-runtime',
    'A small API needs a dependable home',
    'Compute',
    1,
    ['compute', 'managed-services'],
    'A four-person team must launch a booking API in six weeks. Traffic is intermittent and customers expect quick confirmation.',
    'Node.js API and PostgreSQL; 5 requests/s normally, 250/s for ten minutes after campaigns.',
    'Cold-start p95 is 1.4 seconds in the prototype, above the 400 ms booking target; sustained container p95 is 180 ms.',
    'Traffic and latency benchmark',
    'Provisioned concurrency removes most cold starts but stays billable between campaigns; database connections cap at 80.',
    'Serverless API with bounded concurrency',
    'Peaks fit database limits and measured cold starts meet the booking target.',
    'Managed containers with autoscaling',
    'A warm baseline meets latency requirements and one engineer can own releases.',
    '$700/month ceiling; no Kubernetes experience; six-week launch.',
    'Load-test cold and warm paths at 250 requests/s; record p95, errors and connection count.',
  ],
  [
    'cloud-job-queue',
    'Invoices must survive a worker crash',
    'Asynchronous processing',
    2,
    ['async', 'reliability'],
    'Monthly invoice runs time out and customers sometimes receive duplicates. The team needs a recoverable processing design.',
    'HTTP handler generates PDFs and charges accounts synchronously; 40,000 invoices on billing day.',
    'A worker can crash after charging but before acknowledging completion. Queue delivery alone cannot prevent duplicate charges.',
    'Billing failure trace',
    'Three replayed requests produced duplicate charges; the payment provider accepts idempotency keys retained for 24 hours.',
    'Queue with idempotent workers',
    'A durable invoice key and state machine protect external effects across retries.',
    'Managed workflow orchestration',
    'Long-running steps and compensation justify workflow state and additional complexity.',
    'No duplicate charges; invoices within two hours; one-week migration window.',
    'Crash workers before and after the external charge; prove deduplication, dead-letter handling and recovery.',
  ],
  [
    'cloud-database-choice',
    'The inventory service cannot oversell',
    'Database architecture',
    3,
    ['databases', 'scalability'],
    'A retailer is separating inventory from its storefront. Product reads surge during promotions, but checkout must never promise stock already sold.',
    'Relational orders and stock share one PostgreSQL writer; reads reach 8,000/s and reservations 350/s.',
    'The workload uses atomic reservations across warehouse and SKU. A read replica can lag 4 seconds during bursts.',
    'Inventory query and contention report',
    'Most reads are catalog data; reservation writes require a conditional stock check. Reporting scans block the writer.',
    'Relational database with isolated reporting and caching',
    'Transactions preserve reservation invariants while catalog reads leave the writer.',
    'Key-value reservation service',
    'Access patterns and conditional updates can enforce stock rules without cross-item transactions.',
    'No negative stock; reserve p95 under 150 ms; maintain an auditable order link.',
    'Replay competing reservations and replica lag; verify no overselling and measure contention.',
  ],
  [
    'cloud-cache-isolation',
    'Faster pages without leaking customer prices',
    'Caching',
    2,
    ['caching', 'security'],
    "Wholesale buyers see slow catalog pages. A proposed shared cache must preserve each customer's negotiated prices.",
    'CDN fronts an API; product descriptions are public but price responses depend on tenant and contract version.',
    'The current cache key includes only URL. Two tenants requesting the same SKU can receive the same negotiated price.',
    'Cache key audit',
    'Public descriptions tolerate one hour of staleness; contract prices must update within 30 seconds.',
    'Cache public content and bypass private pricing',
    'Public content provides enough acceleration while authorization remains per request.',
    'Tenant-scoped application cache',
    'Keys include authorization scope and contract version with tested invalidation.',
    'No cross-tenant price disclosure; 30-second price freshness; small operations team.',
    'Test tenant switching, revoked access and contract changes against warm caches.',
  ],
  [
    'cloud-private-access',
    'Reach the database without public exposure',
    'Networking',
    2,
    ['networking', 'security'],
    'A support application needs secure database access from cloud workloads and an office. The team wants to eliminate public database endpoints.',
    'Private application subnets, a managed SQL database and an office network connected over the internet.',
    'Office and cloud both use 10.0.0.0/16; a straightforward VPN route would overlap.',
    'Network address and flow inventory',
    'Only support access originates in the office; applications require outbound vendor API calls, not inbound internet access.',
    'Renumber and establish routed private connectivity',
    'Address remediation is feasible and hybrid routing has a clear owner.',
    'Identity-controlled access proxy',
    'Only administrative sessions need access and the proxy can enforce auditing and short-lived identity.',
    'Database never publicly reachable; audited support access; office changes need two weeks.',
    'Prove allowed flows, blocked public access, DNS resolution and recovery after tunnel failure.',
  ],
  [
    'cloud-region-recovery',
    'An outage plan that matches the recovery target',
    'Disaster recovery',
    3,
    ['disaster-recovery', 'reliability'],
    'A scheduling service promises recovery within an hour and at most five minutes of lost bookings. Backups alone have not demonstrated this.',
    'Single-region app, multi-zone database and nightly cross-region snapshots.',
    'The most recent restore rehearsal took 3 hours 20 minutes; snapshot age could lose 24 hours of writes.',
    'Restore rehearsal timings',
    'DNS and secret recovery consumed 50 minutes. Cross-region replication was never enabled or tested.',
    'Warm standby with replicated data',
    'Replication lag and exercised failover meet the one-hour/five-minute targets.',
    'Backup and restore with revised service targets',
    'Business owners accept longer recovery and loss in exchange for lower run cost.',
    'RTO 60 minutes; RPO 5 minutes unless renegotiated; failback must preserve new writes.',
    'Time a regional failover including DNS, secrets, replay and failback; measure actual lost bookings.',
  ],
  [
    'cloud-zero-downtime-migration',
    'Move the customer database during live traffic',
    'Migration',
    4,
    ['migration', 'databases'],
    'A subscription product must move its database to a managed service before its hosting contract ends. Customers write data continuously.',
    '2 TB PostgreSQL database; extensions, scheduled jobs and three dependent services.',
    'One extension is unsupported on the target. The replication trial accumulated 18 minutes of lag during bulk updates.',
    'Migration compatibility and replication report',
    'Four jobs bypass application APIs; no plan reconciles writes after cutover back to the old database.',
    'Replication-led phased cutover',
    'Extension compatibility, lag and a write-fencing protocol are resolved and rehearsed.',
    'Scheduled maintenance migration',
    'An agreed outage permits a simpler consistent copy and validated restart.',
    'Six-week deadline; approved outage under 15 minutes; no silent write loss.',
    'Rehearse extension replacement, checksums, cutover and the point beyond which rollback needs reverse replication.',
  ],
  [
    'cloud-container-platform',
    'Does this team need Kubernetes?',
    'Containers',
    3,
    ['containers', 'operations'],
    'A product team wants repeatable deployments for eight services. Engineers propose Kubernetes while the current on-call rota is already overloaded.',
    'Eight stateless containers, one background worker, managed SQL and weekly deployments.',
    'No custom scheduling or cluster-level operators are required; only two engineers can maintain infrastructure.',
    'Platform requirements and on-call diary',
    'Most incidents stem from missing readiness checks and unsafe releases, not orchestration limits.',
    'Managed container platform',
    'Standard routing, autoscaling and release controls satisfy the service requirements.',
    'Managed Kubernetes',
    'Demonstrated scheduling or platform requirements justify cluster ownership and upgrade capacity.',
    'Two platform-capable engineers; recover releases within ten minutes; three-month delivery horizon.',
    'Deploy a representative service on both options; measure rollback time, operational tasks and resource isolation.',
  ],
  [
    'cloud-event-contracts',
    'Order events arrive twice and out of order',
    'Event-driven integration',
    4,
    ['async', 'reliability'],
    'Fulfillment and billing disagree about order status after an event integration rollout. The architecture must tolerate retries and delayed consumers.',
    'An order service publishes changes after committing SQL transactions; consumers update independent stores.',
    'A crash between commit and publish drops events. Retries can deliver cancellation before creation.',
    'Event delivery fault log',
    'Twenty committed orders had no event; consumer replays duplicated shipment requests.',
    'Transactional outbox with idempotent consumers',
    'Event publication follows committed data and consumers enforce version-aware state transitions.',
    'Synchronous orchestration with durable workflow state',
    'The coupled availability and latency budget are acceptable for centrally coordinated steps.',
    'No lost committed orders; replayable history; no duplicate shipments.',
    'Inject crashes at every boundary; replay reordered events and prove convergence and effect deduplication.',
  ],
  [
    'cloud-object-retention',
    'Archive files without missing a retrieval deadline',
    'Storage',
    1,
    ['storage', 'finops'],
    'An engineering firm keeps large project files for seven years. Most are rarely read, but support must deliver requested files within four hours.',
    'Object storage holds 120 TB; access logs cover only the last 30 days.',
    'A proposed deep archive tier can take longer than the contractual retrieval deadline. Some files are under legal hold.',
    'Retention policy and retrieval sample',
    'Recent projects account for 90% of reads; older project retrievals are uncommon but contractually time-bound.',
    'Lifecycle tiers aligned to retrieval classes',
    "Each project's retrieval deadline and minimum storage duration are checked.",
    'Keep a searchable hot subset with an archive',
    'The hot subset covers contractual urgent requests and retrieval paths are tested.',
    'Seven-year retention; four-hour retrieval for active contracts; preserve legal holds.',
    'Retrieve a representative old project and verify time, completeness, metadata and deletion protection.',
  ],
  [
    'cloud-global-writes',
    'Customers in two regions need consistent balances',
    'Global architecture',
    5,
    ['databases', 'reliability'],
    'A payment-adjacent ledger product is expanding internationally. Customers want local response times while balances must remain consistent during partitions.',
    'Single-writer ledger in one region; a second region serves reads for reporting.',
    'Cross-region round-trip p95 is 180 ms; the requested 60 ms globally consistent write target conflicts with observed network latency.',
    'Regional latency and consistency experiment',
    'During link failure the remote read replica is stale. Product has not defined whether writes may pause.',
    'Home-region writes with local read models',
    'Product accepts write latency and explicitly labels stale reads.',
    'Partitioned account ownership with controlled failover',
    'Account boundaries avoid cross-region transactions and failover fences the former owner.',
    'No double spending; explicit partition behavior; audit every accepted write.',
    'Simulate partition and failover; verify single-writer ownership, balance invariants and latency by region.',
  ],
  [
    'cloud-safe-schema-release',
    'Rollback the app after a database change',
    'Release architecture',
    3,
    ['cicd', 'databases'],
    'A SaaS release failed after renaming a database column. Rolling back the application caused another outage; the team needs a safer release design.',
    'Rolling application deployments share one relational schema; old and new versions coexist for several minutes.',
    'A destructive migration ran before all old instances drained. The rollback binary still expected the deleted column.',
    'Release timeline and schema diff',
    'The load balancer routed 20% of traffic to old instances during migration; backup restoration would discard new writes.',
    'Expand-contract schema migration',
    'Both application versions remain compatible through a measured transition.',
    'Coordinated maintenance release',
    'An approved write freeze and tested restore strategy fit the outage budget.',
    'Weekly releases; rollback under ten minutes; preserve all accepted customer writes.',
    'Run old and new versions together, roll back before contraction, and verify data reconciliation.',
  ],
] as const;

export const cloudArchitectureSeeds: SeedInput[] = decisions.map((d) => ({
  id: d[0],
  title: d[1],
  company: 'Cloud Architecture Studio',
  level: d[3],
  industry: 'Digital services',
  size: 60,
  engineers: 6,
  category: d[2],
  brief: d[5],
  known: [d[6], d[14]],
  skills: [...d[4]],
  facts: [
    ['business', d[5], 'Product owner', true],
    ['architecture', d[6], 'Lead engineer'],
    [
      'requirements',
      d[7],
      'Technical investigation',
      true,
      [...d[4], 'constraints', 'requirements'],
    ],
    ['operations', d[9], 'Operations lead', true],
    [
      'budget',
      d[14] +
        ' Compare monthly infrastructure and operational effort before committing; vendor quotes are not established.',
      'Engineering manager',
    ],
    [
      'team',
      'Six engineers own delivery and on-call. Two can work on this change; validate relevant service experience before selecting a platform.',
      'Engineering manager',
    ],
  ],
  evidence: [
    [
      'architecture',
      d[8],
      'available',
      d[6] + '\n' + d[7] + '\n' + d[9],
      [...d[4], 'test', 'report'],
    ],
    [
      'requirements',
      'Service constraints and acceptance criteria',
      'available',
      d[14],
      ['requirements', 'SLO', 'constraints'],
    ],
    [
      'validation',
      'Proposed architecture experiment',
      'measurement_required',
      d[15] + ' This experiment has not yet been executed.',
      ['validation', 'experiment', 'pilot'],
    ],
  ],
  constraints: [d[14], 'Define an accountable owner and a reversible transition before rollout.'],
  patterns: [
    [d[10], d[11]],
    [d[12], d[13]],
  ],
  flags: [
    ['architecture', 'Selecting a service without testing this constraint: ' + d[7]],
    ['operations', 'Claiming success before executing: ' + d[15]],
  ],
  criteria: [
    'Compare both defensible approaches against the stated constraints.',
    'Address the decision-changing observation: ' + d[7],
    'Specify validation and rollback: ' + d[15],
  ],
}));
